### ISSUE TITLE
change icon when selecting an item

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-wui#870]
### Description of the current behavior

Today
<img width="199" alt="image" src="https://github.com/user-attachments/assets/b2de111a-3db6-4199-b221-d81250c31460">

### Description of the desired behavior

<img width="199" alt="image" src="https://github.com/user-attachments/assets/83233983-f165-48f3-adb5-3a4015de0cc4">

``` css
.resultlist__md-grid-tile__selected--icon {
    position: absolute;
    z-index: 1;
    top: 5px;
    right: 5px;
    color: #000;
    background-color: #fff;
    border-radius: 3px;
    font-size: 15px;
    height: 15px !important;
    width: 15px !important;
}

```

name of icon `radio_button_checked`
